### ISSUE TITLE
Recursive types result in incorrect generated code

### ISSUE THREAD

**Issue by mharmer** [eriktim/protoc-gen-elm#11]
Given the following Protobuf with mutually recursive types:
```
syntax = "proto3";

message Bar {
    Foo b = 1;
}

message Foo {
    map<string, Bar> a = 1;
}
```

And attempting to compile, the Elm compiler will produce the following error:

> Detected errors in 1 module.
> -- ALIAS PROBLEM --------------------------------------------- src\Recursive.elm
> 
> This type alias is part of a mutually recursive set of type aliases.
> 
> 48| type alias Bar =
>                ^^^
> It is part of this cycle of type aliases:
> ...

Note: I think there's also some issues with a single recursively defined type as well:
```
syntax = "proto3";

message Foo {
    Foo a = 1;
    int32 b = 2;
}
```

> Detected errors in 1 module.
> -- TYPE MISMATCH --------------------------------------------- src\Recursive.elm
> 
> The 3rd argument to `optional` is not what I expect:
> 
> 65|         [ Decode.optional 1 (Decode.lazy (\_ -> fooDecoder)) (setA << FooA)
> ...

**Comment by eriktim** [comment]
Thanks for your report! There is actually already a recursion detection in place (not yet released), but it doesn't seem to handle this particular case properly. I'm working on a fix.
