### ISSUE TITLE
Incorrect imports generated when multiple proto files compiled

### ISSUE THREAD

**Issue by drivehappy** [eriktim/protoc-gen-elm#2]
My understanding is that this generator will "bake" all messages that exist under the same package name into a single file. When I attempt to compile 2 or more .proto files it appears an incorrect `import` on the same package name is generated in the resulting Elm code.

`a.proto`:
```
syntax = "proto3";

package fakepackage;

import "b.proto";

message RootFoo {
  Foo foo = 1;
}
```

`b.proto`:
```
syntax = "proto3";

package fakepackage;

message Foo {
  enum Bar {
    Foo = 0;
  }
}
```

And compilation:
`protoc --elm_out=. a.proto b.proto`

Compiles successfully into a `Fakepackage.elm`. However, when I attempt to compile with Elm, it complains that the module imports form a cycle. Particularly, the following block is generated:
```
module Fakepackage exposing
   ~snip~

import Fakepackage
import Protobuf.Decode as Decode
import Protobuf.Encode as Encode
```

I'm not too familiar with Elm currently, but it seems to be a protobuf codegen issue with an incorrect `import Fakepackage` being generated.

**Comment by eriktim** [comment]
This indeed happens when you provide both files (not if you run `protoc --elm_out=. a.proto`). Thanks for reporting this!
