### ISSUE TITLE
Cannot use imported proto message using default package names

### ISSUE THREAD

**Issue by rlefevre** [eriktim/protoc-gen-elm#5]
Hi, 

Just starting with protocol buffers, so I'm not sure if this is an issue or not.

Using protoc-gen-elm@1.0.0-beta-1 and given the following proto files:

`name.proto`
```
syntax = "proto2";

message Name {
    required string name = 1;
}
```

`hello.proto`
```
syntax = "proto2";

import "name.proto";

message Hello {
    required Name name = 1;
}
```
the generated `Hello.elm` module will import `Name` without exposing its messages types:
```
import Name
import Protobuf.Decode as Decode
import Protobuf.Encode as Encode

{-| Hello
-}
type alias Hello =
    { name : Maybe Name
    }
```
so it does not compile:
```
-- NAMING ERROR ------------------------------------------------------ Hello.elm

I cannot find a `Name` type:
```

If I add for example `package name;` in `name.proto` and use `name.Name` in `hello.proto`, it compiles successfully.

**Comment by eriktim** [comment]
Thanks for reporting this @rlefevre! This is indeed a bug. It should use the package `Name` by default if is not provided.
