### ISSUE TITLE
proto2 repeated enumerations without packed=true decoding fail

### ISSUE THREAD

**Issue by rlefevre** [eriktim/protoc-gen-elm#6]
Using protoc-gen-elm@1.0.0-beta-1 and eriktim/elm-protocol-buffers 1.0.0, `repeated` enumerations decoding fail using "proto2" syntax if `[packed=true]` is not set. I have not tested with other scalar values than enumerations.

For example:
```
syntax = "proto2";

message Message {
  enum Enum {
    default = 0;
    other = 1;
  }
  repeated Enum enums = 1;
}
```
would fail to be decoded, however it would work with:
```
syntax = "proto2";

message Message {
  enum Enum {
    default = 0;
    other = 1;
  }
  repeated Enum enums = 1 [packed=true];
}
```

Maybe this could be added for now in the "Known Limitations"?

**Comment by eriktim** [comment]
Thanks for reporting this @rlefevre!
Can you confirm the generated Elm code is the same for both cases. I guess this bug occurs in the eriktim/elm-protocol-buffers library and not in this generator.

**Comment by rlefevre** [comment]
Thanks @eriktim. You're right, the generated Elm code is the same for both cases.
