### ISSUE TITLE
Incorrect code generated with type names

### ISSUE THREAD

**Issue by mharmer** [eriktim/protoc-gen-elm#7]
When compiling a single proto file that imports another, the referenced types don't seem to be correct:

`sub.proto`:
```
syntax = "proto3";

package Foo;

message Baz2 {
	int32 field_a = 1;
}
```
`main.proto`:
```
syntax = "proto3";

import "sub.proto";

package Foo;

message Baz {
	Baz2 field_a = 1;
}
```

Compiled with: `protoc --elm_out=. main.proto sub.proto`

Produces incorrect code:
```
{-| `Baz2` message
-}
type alias Baz2 =
    { fieldA : Int
    }


{-| `Baz` message
-}
type alias Baz =
    { fieldA : Maybe FooBaz2
    }
```
Compiler error for reference:
```
I cannot find a `FooBaz2` type:

57|     { fieldA : Maybe FooBaz2
```

It seems as though the package name is incorrectly being added to the name of the type.

**Comment by drivehappy** [comment]
@eriktim I took a closer look at this, and I think it's caused by this [typename conversion](https://github.com/eriktim/protoc-gen-elm/blob/master/src/Mapper.elm#L475). Unfortunately removing that seems to break the Elm generated from the protoc plugin.proto, particularly around nested message types.

**Comment by eriktim** [comment]
As stated [here](https://developers.google.com/protocol-buffers/docs/style#packages), `package` must be in lowercase. You should use `package foo;` which will result in the right code.

Some technical background: It indeed has to do with the function you are referring to, but protobuf does not allow me to see the difference between a type `Baz2` that is nested under `Foo` (`Foo.Baz2`) or which is part of a package `Foo` (`Foo.Baz2`). The dot gets removed here as it is not allowed in an Elm type.

**Comment by mharmer** [comment]
Thanks, that resolves it. Not to nit-pick, but I would consider that link to be a style-guide only and pedantically speaking it says package names _should_ be lowercase, not that they must be.

**Comment by eriktim** [comment]
I guess you're right, but let's say your _fix_ is by far easier than mine ;-)
