### ISSUE TITLE
Large protobuf messages produce a failure

### ISSUE THREAD

**Issue by mharmer** [eriktim/protoc-gen-elm#8]
When running `protoc` against a large set of protobuf messages, protoc-gen-elm returns with a failure: `Failed parsing request from protoc`

This seems to be caused by the stdin pipe size limit of 64k bytes (at least under Ubuntu 19.04). I think some sort of buffering here may be needed before the data is base64 encoded and send through the `request` port.

**Comment by eriktim** [comment]
Thanks for reporting this @mharmer! Are you willing to share your `.proto`  file(s) (privately)? It'll make debugging easier for me.

**Comment by mharmer** [comment]
I can't share the original ones, but here's a single proto file that reproduces the issue: [large.proto.tar.gz](https://github.com/eriktim/protoc-gen-elm/files/3241931/large.proto.tar.gz)

Additional info:
- I observed this issue under Linux (Ubuntu 19.04), but I don't think I've seen the same issue when running under Windows 10.

**Comment by eriktim** [comment]
The 64k chunk size was indeed also the default in Arch. Thanks for your contribution @mharmer.
